### ISSUE TITLE
API Inaccessible via CORS

### ISSUE THREAD

**Issue by Sukadia** [calzoneman/aeiou#13]
Hello!

I was really interested in using the API you have running (in particular, as a TTS for stream donations since it'd be really funny), but I get the `No 'Access-Control-Allow-Origin' header is present on the requested resource` error.

Is this intentional?

**Comment by calzoneman** [comment]
Hi,

Could you describe (with sample code) how you're trying to use the API?

**Comment by Sukadia** [comment]
Sure- so I'm trying to make a custom widget through StreamElements, so streamelements.com is the one making the requests and I'm just calling a `await fetch(`https://tts.cyzon.us/tts?text=${encodeURIComponent(event.message)}`` to receive the audio file to then read out the message.

**Comment by calzoneman** [comment]
Is there a particular reason that you're using `fetch` for this (grabbing the raw byte stream of the result), rather than the [`Audio`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio) API that JavaScript already provides?

I think the reason you're getting that error is because `fetch` is subject to additional CSP restrictions by default (since it can make essentially arbitrary requests), which do not apply to simply playing back audio/video streams through the native mechanisms.

I think if you were to do something like this, then it should work:

```
let audio = new Audio('https://tts.cyzon.us/tts?text=aeiou');
audio.addEventListener('canplay', () => audio.play());
```

**Comment by calzoneman** [comment]
Also, just so you know: certain inputs can cause DECTalk to render audio that you probably wouldn't want playing back on your stream, for example, long strings of Unicode characters can cause it to read out nonsense for upwards of 10 minutes, and certain combinations of voice manipulation commands can cause it to produce screeching noises that could be described as "ear rape".  So if you plan to use this to read out messages from your viewers, you probably want to do some minimal level of filtering before you pass the text along to this API.

**Comment by Sukadia** [comment]
Oh, you're completely right! I had just assumed I needed the direct link to the audio file before passing it into Audio() without realizing the redirect would be handled correctly. Appreciate the help, it works flawlessly now.

And for sure; it's definitely playing with fire if there's no length check of the audio and other things with the text itself. With great power comes great responsibility.
