### ISSUE TITLE
Headless server setup?

### ISSUE THREAD

**Issue by MonkaKokosowa** [calzoneman/aeiou#20]
Is there any way to setup docker container on a headless server without X server?

**Comment by calzoneman** [comment]
Hi,

The docker image itself doesn't require a live X display, it just needs the mounted wineprefix directory to have DECtalk installed in it, which is the part that requires a display (since DECtalk is a Windows 95 application with a graphical installer).  What I do is run the steps on https://github.com/calzoneman/aeiou#installation-under-docker using my local Linux desktop, and then I transfer the resulting wineprefix folder to a headless server to run the image.

I don't really recommend trying to install DECtalk without using the Docker image, since on most modern Linux distributions trying to install the right dependencies to get a 32-bit compatible installation of a compatible version of Wine is annoying.

**Comment by MonkaKokosowa** [comment]
I see, thanks a lot!
