### ISSUE TITLE
The TTS sounds a bit... off

### ISSUE THREAD

**Issue by JaCoB123456798** [calzoneman/aeiou#4]
It pronounces things slightly differently than in-game and has other small differences. It also doesn't sound exactly the same as in-game. Did the game maybe apply filters over it? Is it possible you could also do it so it's a perfect replica of the in-game text to speech?

For example:
[In-game aeiou](https://drive.google.com/file/d/1GSrpFqMyeFyomWBZbzZkojd3TcHkrsGK/view?usp=sharing)
vs
[Generated aeiou](https://drive.google.com/file/d/1fk_HFOj_JXGAAYERF0hLTFSQ28OXP9-D/view?usp=sharing)
and "[snake? snake! snaaaaaaaaaaaaaaaaaaake!](https://drive.google.com/file/d/1pUhYDyngCx_tRtQ7MODFzjPTkHnvJxM4/view?usp=sharing)" is pronounced differently

I am using the http://tts.cyzon.us/tts?text= version.

Edit: I also forgot to mention that it get's quieter the higher pitch it is modified to be.

**Comment by calzoneman** [comment]
I assume that by "in-game" you are referring to Moonbase Alpha?

It's possible that game uses a different version of the DECTalk engine, or that it applies post-processing effects (this project is just using DECTalk's built-in WAV output, from a version of DECTalk I had lying around that I haven't done any particular deep research into).

Regardless, this project was never intended to be a perfect recreation of Moonbase Alpha's text to speech engine, I only mentioned it in the README because it happens to also be based on DECTalk.  I really just took https://github.com/whatsecretproject/SharpTalk, reverted it back from FonixTalk to DECTalk, fixed up a few incompatibilities, and wired it up to a WAV output with a web interface.

**Comment by RiskiVR** [comment]
The version on the web api is DECTalk 4.6.1, Moonbase Alpha uses DECTalk 4.6.4.
The author would have to update the web api DECTalk backend to use 4.6.4 if you want it to be fully accurate to Moonbase Alpha.

Also, if you want that same post effect you'd hear in-game, you would have to upsample the audio from 11025hz to 44100 with zero order interpolation.
